"""empty message

Revision ID: 166797d94fcb
Revises: 2f33ad997d78
Create Date: 2022-05-02 19:15:48.683565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166797d94fcb'
down_revision = '2f33ad997d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_todo_user_id_user'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')
        batch_op.drop_index('ix_user_username')
        batch_op.create_index(batch_op.f('ix_$(column_0_label)s'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_$(column_0_label)s'))
        batch_op.create_index('ix_user_username', ['username'], unique=False)
        batch_op.create_index('ix_user_email', ['email'], unique=False)

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_todo_user_id_user'), type_='foreignkey')

    # ### end Alembic commands ###
